/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_johnhany_grayprocessjni_ImageProc */

#ifndef _Included_net_johnhany_grayprocessjni_ImageProc
#define _Included_net_johnhany_grayprocessjni_ImageProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_johnhany_grayprocessjni_ImageProc
 * Method:    grayProc
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_net_johnhany_grayprocessjni_ImageProc_grayProc
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
